drop table if exists users, items, bookings, comments;

CREATE TABLE if not exists users
(
    id    int generated by default as identity primary key,
    name  varchar(255) not null,
    email varchar(255) not null unique
);

CREATE TABLE if not exists items
(
    id          int generated by default as identity primary key,
    name        varchar(255),
    description varchar(255),
    available   boolean,
    owner_id    bigint references users (id)
);

CREATE TABLE if not exists bookings
(
    id         int generated by default as identity primary key,
    start_date timestamp without time zone,
    end_date   timestamp without time zone,
    item_id    int references items (id),
    booker_id  int references users (id),
    status     varchar(20)
);

CREATE TABLE if not exists comments
(
    id        int generated by default as identity primary key,
    text      varchar(255) not null,
    item_id   int references items (id) on DELETE cascade,
    author_id int references users (id) on DELETE cascade,
    created   timestamp without time zone default current_timestamp
)